### ISSUE TITLE
 Parse error: syntax error

### ISSUE THREAD

**Issue by Hubert9311** [outscraper/outscraper-php#4]
When I'm trying to install via composer I got error on the line 74 unexpected '|' using php 7.49 and current version library

**Comment by maevelevie** [comment]
Can confirm. This library used mixed return types (e.g. string|array) that are only supported in PHP 8.
That pretty much renders any version unusable for those who have to (also) support PHP 7 hosting setups.
However, all versions of the package are listed as compatible with PHP >=7.4.
